"use strict";

// Generated by tools/update_manifests.py. Do not edit manually.
(() => {
    const files = [
        "./levels/level_001.json",
        "./levels/level_002.json",
        "./levels/level_003.json",
        "./levels/level_004.json",
        "./levels/level_005.json"
    ];
    const campaigns = [
        { folder: "Flags", level_count: 5, file_width: 3 },
        { folder: "Other", level_count: 6, file_width: 3 },
        { folder: "Pokemon", level_count: 1025, file_width: 4 },
        { folder: "Superheroes", level_count: 44, file_width: 3 }
    ];

    for (const campaign of campaigns) {
        files.push(`./levels/${campaign.folder}/campaign.json`);

        for (let level_number = 1; level_number <= campaign.level_count; level_number += 1) {
            const file_number = String(level_number).padStart(
                campaign.file_width,
                "0"
            );
            files.push(
                `./levels/${campaign.folder}/level_${file_number}.json`
            );
        }
    }

    globalThis.CHOOBS_CAMPAIGN_FILES = Object.freeze(files);
})();
