"use strict";

// Generated by tools/update_manifests.py. Do not edit manually.
// The manifest updater workflow replaces this bootstrap table with exact hashes.
(() => {
    const revisions = Object.freeze({});

    globalThis.CHOOBS_LEVEL_REVISION_ALGORITHM = "sha256";
    globalThis.CHOOBS_LEVEL_MANIFEST_REVISION = "bootstrap-v1";
    globalThis.CHOOBS_LEVEL_REVISIONS = revisions;
})();
